package org.besus.meice.oramtt.util;

public interface Constants {
	String ERDFRAME_NEW_BUTTON_TOOLTIPTEXT = "New ER Diagram";
	String ERDFRAME_OPEN_BUTTON_TOOLTIPTEXT = "Open";
	String ERDFRAME_SAVE_BUTTON_TOOLTIPTEXT = "Save";
	String ERDFRAME_SAVEAS_BUTTON_TOOLTIPTEXT = "Save As";
	String ERDFRAME_UNDO_BUTTON_TOOLTIPTEXT = "Undo";
	String ERDFRAME_REDO_BUTTON_TOOLTIPTEXT = "Redo";
	String ERDFRAME_DELETE_BUTTON_TOOLTIPTEXT = "Delete";
	String ERDFRAME_RUN_BUTTON_TOOLTIPTEXT = "Create Tables";
	String ERDFRAME_ENTITY_BUTTON_TOOLTIPTEXT = "Entity";
	String ERDFRAME_ATTRIBUTE_BUTTON_TOOLTIPTEXT = "Atribute";
	String ERDFRAME_RELATION_BUTTON_TOOLTIPTEXT = "Relation";
}
